name: 'CI/CD'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-check:
    name: Lint check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get node version
        id: node-version
        run: |
          echo "::set-output name=nodeVersion::$(node --version)"

      - name: Load cached node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}_modules_${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

